/**
 * AI-generated match-explanation generator for TalentFlow.
 *
 * Given a (job, candidate, match_percent) tuple, this module asks Claude
 * to produce a short Dutch-language explanation describing WHY the candidate
 * is a fit, the strengths to highlight, and the gaps a recruiter should verify.
 *
 * Model strategy:
 * - Primary: `claude-haiku-4-5-20251001` — fast and cheap; explanations are
 *   only generated for the top-N matches a recruiter actually inspects, so we
 *   default to the cheaper model. Empirically Haiku produces sufficiently
 *   nuanced two-to-three-sentence rationales for this task.
 * - Fallback: `claude-opus-4-7` — used when Haiku returns a transient error
 *   (429/5xx). Opus is also the model we use for the heavier resume-parsing
 *   workload (see `aiParser.ts`).
 *
 * Mock mode: when `ANTHROPIC_API_KEY` is missing in dev, we fall back to a
 * deterministic Dutch template based on the input. In production a missing
 * key throws — we never silently return mocked data to a paying tenant.
 *
 * Output is strict JSON; we extract via first-`{` / last-`}` slicing to
 * tolerate the occasional preamble or markdown fence Claude can emit.
 */

import Anthropic from '@anthropic-ai/sdk';
import { z } from 'zod';
import { logger } from '../middleware/errorHandler';

// ─────────────────────────────────────────────────────────────────────────────
// Public types
// ─────────────────────────────────────────────────────────────────────────────

export interface MatchExplanationInput {
  job: {
    title: string;
    description?: string;
    required_skills?: string[];
  };
  candidate: {
    name: string;
    current_position?: string;
    ai_summary?: string;
    skills?: Array<{ skill: string; score: number }>;
    years_of_experience?: number;
  };
  /** Computed match percentage (0-100) — passed to the prompt for context. */
  match_percent: number;
  /**
   * Sprint Q3.3 — Talent-Fit signaal.
   *
   * Aantal historische, succesvolle hires van deze tenant die qua embedding
   * op de huidige kandidaat lijken. Wordt door de Talent-Fit pipeline
   * gevuld via `findSimilarPastHires`. Wanneer aanwezig (en > 0) krijgt
   * Claude expliciet de instructie om een `similar_hires_note` veld te
   * vullen met een korte verwijzing zoals "Lijkt op 3 eerder aangenomen
   * frontend developers".
   *
   * Optioneel — oudere callers blijven werken. 0 betekent: geen note vragen.
   */
  similar_hires_count?: number;
}

export interface MatchExplanation {
  /** 2-3 line Dutch explanation. */
  text: string;
  /** 2-4 strong matches, expressed as skill names. */
  strengths: string[];
  /** 0-3 gaps the recruiter should verify. */
  gaps: string[];
  /**
   * Optionele Talent-Fit referentie — pas gevuld als de prompt een
   * `similar_hires_count > 0` ontving. Eén korte zin, NL, observerend
   * geformuleerd ("Lijkt op N eerder aangenomen ..."). Niet bedoeld om de
   * core-uitleg te vervangen, maar als secundair signaal voor de UI.
   */
  similar_hires_note?: string;
  /** True if the result was generated by the dev-mode mock instead of Claude. */
  mocked?: boolean;
  /**
   * Diagnostic info — niet bedoeld voor de UI maar voor `ai_events` logging.
   * Optioneel zodat oudere callers blijven werken.
   */
  _meta?: {
    latencyMs: number;
    inputTokens?: number;
    outputTokens?: number;
    mocked: boolean;
    model: string;
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────────────────────

const PRIMARY_MODEL = 'claude-haiku-4-5-20251001';
const FALLBACK_MODEL = 'claude-opus-4-7';
const MAX_TOKENS = 600;
/** Truncation guard for the job description we feed the prompt. */
const MAX_DESCRIPTION_CHARS = 4_000;
const MAX_SUMMARY_CHARS = 2_000;
const MAX_STRENGTHS = 4;
const MAX_GAPS = 3;

const SYSTEM_PROMPT = [
  "Je bent een Nederlandstalige recruitment-AI die vacature-kandidaat matches uitlegt voor recruiters in een ATS.",
  '',
  'JOUW DOEL:',
  '- Schrijf 2-3 zinnen die uitleggen WAAROM deze kandidaat past bij deze vacature, in het Nederlands.',
  '- Noem maximaal 4 sterke skill-matches (strengths).',
  '- Noem 0-3 gaps die de recruiter moet checken voordat hij contact opneemt.',
  '- Wanneer in de input een veld "Vergelijkbare succesvolle hires" met een aantal > 0 staat,',
  '  voeg een korte observerende zin toe in het veld `similar_hires_note` ("Lijkt op N',
  '  eerder aangenomen <korte rolomschrijving>"). Laat het veld weg of leeg als het',
  '  aantal 0 of niet vermeld is.',
  '',
  'OBJECTIVITEIT (EU AI Act compliance):',
  '- Wees objectief en feitelijk; vermijd subjectieve oordelen.',
  '- Focus op observaties van data (skills, jaren ervaring, huidige positie).',
  '- Schrijf in observerende toon ("Kandidaat heeft 5 jaar ervaring met..."), niet in adviserende toon ("Deze kandidaat is perfect voor...").',
  '- Beschrijf nooit demografische of niet-werkgerelateerde kenmerken.',
  '- Gebruik geen waarderende bijvoeglijke naamwoorden zoals "uitstekend", "perfect", "geweldig".',
  '',
  'STRIKT OUTPUT-FORMAAT:',
  '- Antwoord UITSLUITEND met een geldig JSON-object — geen begeleidende tekst.',
  '- GEEN markdown-fences, GEEN voor- of nawoord.',
  '- Het JSON-object moet de keys text, strengths, gaps bevatten.',
  '- text: string (2-3 Nederlandse zinnen).',
  '- strengths: array van 2-4 skill-namen (strings).',
  '- gaps: array van 0-3 korte beschrijvingen (strings).',
  '- similar_hires_note (optioneel): string van max ~120 tekens of weglaten.',
].join('\n');

// ─────────────────────────────────────────────────────────────────────────────
// zod schema voor de AI-respons
// ─────────────────────────────────────────────────────────────────────────────

const matchExplanationSchema = z.object({
  text: z.string().trim().min(1).max(1_500),
  strengths: z.array(z.string().trim().min(1).max(120)).max(MAX_STRENGTHS).default([]),
  gaps: z.array(z.string().trim().min(1).max(240)).max(MAX_GAPS).default([]),
  // Optioneel veld dat alleen wordt ingevuld als de prompt
  // `similar_hires_count > 0` ontving. Lege string of weggelaten = geen note.
  similar_hires_note: z.string().trim().max(240).optional(),
});

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Pak het eerste { en laatste } uit een respons en parse als JSON.
 * Tolerant tegen markdown-fences of preamble-tekst die het model soms toevoegt.
 */
function extractJson(raw: string): unknown {
  const first = raw.indexOf('{');
  const last = raw.lastIndexOf('}');
  if (first === -1 || last === -1 || last <= first) {
    throw new Error(
      `matchExplanation: geen JSON-object gevonden in respons (preview: ${raw.slice(0, 400)})`
    );
  }
  const slice = raw.slice(first, last + 1);
  try {
    return JSON.parse(slice);
  } catch (err) {
    throw new Error(
      `matchExplanation: JSON.parse faalde (${(err as Error).message}); preview: ${raw.slice(0, 400)}`
    );
  }
}

function getResponseText(message: Anthropic.Messages.Message): string {
  for (const block of message.content) {
    if (block.type === 'text') {
      return block.text;
    }
  }
  return '';
}

function isTransientApiError(err: unknown): boolean {
  const e = err as { status?: number; statusCode?: number };
  const status = e?.status ?? e?.statusCode;
  return status === 429 || status === 500 || status === 502 || status === 503;
}

function clampPercent(percent: number): number {
  if (Number.isNaN(percent)) return 0;
  if (percent < 0) return 0;
  if (percent > 100) return 100;
  return Math.round(percent);
}

// ─────────────────────────────────────────────────────────────────────────────
// Mock fallback (alleen dev-zonder-API-key)
// ─────────────────────────────────────────────────────────────────────────────

function buildMockExplanation(input: MatchExplanationInput, latencyMs = 0): MatchExplanation {
  const percent = clampPercent(input.match_percent);
  const topSkills = (input.candidate.skills ?? [])
    .slice()
    .sort((a, b) => b.score - a.score)
    .slice(0, MAX_STRENGTHS)
    .map((s) => s.skill);

  const requiredSet = new Set(
    (input.job.required_skills ?? []).map((s) => s.toLowerCase().trim())
  );
  const candidateSkillSet = new Set(
    (input.candidate.skills ?? []).map((s) => s.skill.toLowerCase().trim())
  );
  const missing = (input.job.required_skills ?? [])
    .filter((s) => !candidateSkillSet.has(s.toLowerCase().trim()))
    .slice(0, MAX_GAPS);

  const matchingRequired = (input.candidate.skills ?? [])
    .filter((s) => requiredSet.has(s.skill.toLowerCase().trim()))
    .map((s) => s.skill);

  const strengths = (matchingRequired.length > 0 ? matchingRequired : topSkills).slice(
    0,
    MAX_STRENGTHS
  );

  const yearsLine =
    typeof input.candidate.years_of_experience === 'number'
      ? ` met ${input.candidate.years_of_experience} jaar werkervaring`
      : '';
  const positionLine = input.candidate.current_position
    ? ` (huidige functie: ${input.candidate.current_position})`
    : '';

  const text = [
    `Mock-uitleg: kandidaat ${input.candidate.name}${positionLine} matcht op ${percent}% met de vacature "${input.job.title}"${yearsLine}.`,
    strengths.length > 0
      ? `Sterkste skill-overlap: ${strengths.join(', ')}.`
      : 'Skill-overlap kon niet worden vastgesteld zonder AI.',
    'Deze samenvatting is gegenereerd zonder Anthropic API-key — configureer ANTHROPIC_API_KEY voor echte uitleg.',
  ].join(' ');

  // Mock-equivalent van de Talent-Fit similar_hires_note. Alleen genereren
  // als de caller daadwerkelijk een aantal > 0 doorgaf — anders silent skip.
  const similarHiresCount = input.similar_hires_count ?? 0;
  const similarHiresNote =
    similarHiresCount > 0
      ? `Lijkt op ${similarHiresCount} eerder aangenomen ${
          input.candidate.current_position
            ? input.candidate.current_position.toLowerCase()
            : 'kandidaat'
        }${similarHiresCount > 1 ? 's' : ''}.`
      : undefined;

  return {
    text,
    strengths,
    gaps: missing,
    similar_hires_note: similarHiresNote,
    mocked: true,
    _meta: {
      latencyMs,
      mocked: true,
      model: `${PRIMARY_MODEL}-mock`,
    },
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Anthropic-client (lazy singleton)
// ─────────────────────────────────────────────────────────────────────────────

let cachedClient: Anthropic | null = null;

function getAnthropicClient(): Anthropic {
  if (!cachedClient) {
    const apiKey = process.env.ANTHROPIC_API_KEY;
    if (!apiKey) {
      throw new Error(
        'ANTHROPIC_API_KEY ontbreekt: vereist voor match-explanations in productie.'
      );
    }
    cachedClient = new Anthropic({ apiKey });
  }
  return cachedClient;
}

let warnedAboutMissingKey = false;
function shouldUseMockFallback(): boolean {
  if (process.env.ANTHROPIC_API_KEY) return false;
  // Productie mag NOOIT stilzwijgend mock-data wegschrijven.
  if (process.env.NODE_ENV === 'production') return false;

  if (!warnedAboutMissingKey) {
    logger.warn(
      '[matchExplanation] ANTHROPIC_API_KEY ontbreekt — dev-fallback met mock-explanation actief'
    );
    warnedAboutMissingKey = true;
  }
  return true;
}

// ─────────────────────────────────────────────────────────────────────────────
// Prompt construction
// ─────────────────────────────────────────────────────────────────────────────

function buildUserPrompt(input: MatchExplanationInput): string {
  const percent = clampPercent(input.match_percent);
  const description = (input.job.description ?? '').slice(0, MAX_DESCRIPTION_CHARS);
  const requiredSkills = input.job.required_skills ?? [];
  const skills = input.candidate.skills ?? [];
  const summary = (input.candidate.ai_summary ?? '').slice(0, MAX_SUMMARY_CHARS);

  const skillsBlock =
    skills.length > 0
      ? skills
          .slice()
          .sort((a, b) => b.score - a.score)
          .map((s) => `- ${s.skill} (score ${s.score}/10)`)
          .join('\n')
      : '(geen geanalyseerde skills beschikbaar)';

  const requiredBlock =
    requiredSkills.length > 0
      ? requiredSkills.map((s) => `- ${s}`).join('\n')
      : '(geen expliciete required_skills opgegeven)';

  // Sprint Q3.3 — similar past hires signaal. Alleen tonen als > 0 zodat
  // Claude geen lege referentie verzint wanneer er geen historie is.
  const similarHiresLine =
    typeof input.similar_hires_count === 'number' && input.similar_hires_count > 0
      ? `Vergelijkbare succesvolle hires: ${input.similar_hires_count}`
      : 'Vergelijkbare succesvolle hires: 0';

  return [
    `Match-score: ${percent}%`,
    similarHiresLine,
    '',
    '=== VACATURE ===',
    `Titel: ${input.job.title}`,
    'Beschrijving:',
    description || '(geen beschrijving)',
    '',
    'Vereiste skills:',
    requiredBlock,
    '',
    '=== KANDIDAAT ===',
    `Naam: ${input.candidate.name}`,
    input.candidate.current_position
      ? `Huidige functie: ${input.candidate.current_position}`
      : 'Huidige functie: (onbekend)',
    typeof input.candidate.years_of_experience === 'number'
      ? `Werkervaring: ${input.candidate.years_of_experience} jaar`
      : 'Werkervaring: (onbekend)',
    '',
    'AI-samenvatting:',
    summary || '(geen AI-samenvatting beschikbaar)',
    '',
    'Skills (uit CV):',
    skillsBlock,
    '',
    'Genereer nu de JSON-uitleg volgens de afgesproken vorm.',
  ].join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generate a Dutch-language explanation of why a candidate matches a job.
 *
 * The function is safe to call in dev without an API key — it returns a
 * deterministic mock based on the inputs. In production a missing key throws.
 */
export async function generateMatchExplanation(
  input: MatchExplanationInput
): Promise<MatchExplanation> {
  const startedAt = Date.now();
  if (shouldUseMockFallback()) {
    return buildMockExplanation(input, Date.now() - startedAt);
  }

  const client = getAnthropicClient();
  const userPrompt = buildUserPrompt(input);

  const callModel = async (model: string): Promise<Anthropic.Messages.Message> => {
    return client.messages.create({
      model,
      max_tokens: MAX_TOKENS,
      system: SYSTEM_PROMPT,
      messages: [{ role: 'user', content: userPrompt }],
    });
  };

  let response: Anthropic.Messages.Message;
  let modelUsed = PRIMARY_MODEL;
  try {
    response = await callModel(PRIMARY_MODEL);
  } catch (err) {
    if (!isTransientApiError(err)) throw err;
    logger.warn('[matchExplanation] primary model faalde — retry op fallback', {
      model: PRIMARY_MODEL,
      fallback: FALLBACK_MODEL,
      error: (err as Error).message,
    });
    response = await callModel(FALLBACK_MODEL);
    modelUsed = FALLBACK_MODEL;
  }

  const rawText = getResponseText(response);
  if (!rawText) {
    throw new Error('matchExplanation: lege respons van Claude (geen text-block).');
  }

  const candidate = extractJson(rawText);
  const validated = matchExplanationSchema.safeParse(candidate);
  if (!validated.success) {
    const issues = validated.error.issues
      .map((i) => `${i.path.join('.')}: ${i.message}`)
      .join('; ');
    throw new Error(
      `matchExplanation: schema-validatie faalde (${issues}); preview: ${rawText.slice(0, 400)}`
    );
  }

  // Strip lege similar_hires_note ("") of plak 'm door als hij niet-leeg is.
  // Wanneer de caller geen similar_hires_count > 0 doorgaf maar Claude er
  // toch een verzon, retourneren we 'm niet — dit voorkomt valse positives.
  const callerSentSignal =
    typeof input.similar_hires_count === 'number' && input.similar_hires_count > 0;
  const noteRaw = (validated.data.similar_hires_note ?? '').trim();
  const similarHiresNote =
    callerSentSignal && noteRaw.length > 0 ? noteRaw : undefined;

  return {
    text: validated.data.text,
    strengths: validated.data.strengths.slice(0, MAX_STRENGTHS),
    gaps: validated.data.gaps.slice(0, MAX_GAPS),
    similar_hires_note: similarHiresNote,
    _meta: {
      latencyMs: Date.now() - startedAt,
      inputTokens: response.usage?.input_tokens ?? undefined,
      outputTokens: response.usage?.output_tokens ?? undefined,
      mocked: false,
      model: modelUsed,
    },
  };
}
