/**
 * Public career-page types — Sprint Q2.2.
 *
 * Shapes returned by the public career-page API endpoints
 * (`/api/career-pages/public/...`) and consumed by the SSR career-page,
 * job-detail page and application form.
 *
 * Kept intentionally separate from the admin-builder types in
 * `hooks/useCareerPages.ts` so the public renderer can evolve without
 * pulling React-Query / mock-data noise into Server Components.
 */

export type Locale = "nl" | "en";

export interface PublicBranding {
  brand_name: string;
  logo_url?: string | null;
  favicon_url?: string | null;
  primary_color?: string | null;
  accent_color?: string | null;
  font_family?: string | null;
}

// Block-renderer discriminated union. Builder may emit unknown future
// types — we render those as a no-op so old SSR can survive new data.
export type BlockType =
  | "hero"
  | "features"
  | "jobs_list"
  | "about"
  | "testimonials"
  | "cta"
  | "footer"
  | "custom_html";

export interface BaseBlock<T extends BlockType = BlockType> {
  id: string;
  type: T;
  data: Record<string, unknown>;
}

export type Block = BaseBlock;

export interface PublicJob {
  id: string;
  title: string;
  department?: string | null;
  location?: string | null;
  description?: string | null;
  description_html?: string | null;
  employment_type?: string | null;
  salary_min?: number | null;
  salary_max?: number | null;
  salary_currency?: string | null;
  remote?: boolean | null;
  posted_at?: string | null;
  closes_at?: string | null;
}

export interface PublicCareerPage {
  id: string;
  slug: string;
  template_id?: string | null;
  blocks: Block[];
  branding: PublicBranding;
  seo_title?: string | null;
  seo_description?: string | null;
  og_image_url?: string | null;
  locale: Locale;
  ga4_id?: string | null;
  /**
   * JobPosting JSON-LD array (or single object) generated by backend.
   * Injected via <script type="application/ld+json"> for SEO.
   */
  structured_data_jsonld: unknown;
  jobs: PublicJob[];
}

export interface PublicFormFieldOption {
  value: string;
  label: string;
}

export type PublicFormFieldType =
  | "text"
  | "textarea"
  | "email"
  | "phone"
  | "dropdown"
  | "checkbox"
  | "file";

export interface PublicFormField {
  id: string;
  /** Internal name used as form-data key. */
  name: string;
  type: PublicFormFieldType;
  label: string;
  placeholder?: string | null;
  help_text?: string | null;
  required?: boolean;
  options?: PublicFormFieldOption[];
  /** For file fields: max bytes + accepted mime/extensions. */
  max_size_bytes?: number | null;
  accept?: string | null;
}

export interface PublicJobForm {
  fields: PublicFormField[];
}
